# Generated by Django 3.0.5 on 2020-04-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0003_auto_20200406_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='hotelapi.Hotel'),
        ),
    ]
