# Generated by Django 3.0.5 on 2020-04-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0006_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('name', 'address', 'geolocation')},
        ),
    ]
