# Generated by Django 3.0.5 on 2020-04-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0007_auto_20200428_2125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together=set(),
        ),
    ]
